apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  {{- with .Values.db.default }}
  postgres_user: {{ .user }}
  postgres_password: {{ .password }}
  postgres_db_name: {{ .db_name }}
  {{- end }}